---
title: "R Notebook"
output: html_notebook
---

```{r}
##Libraries
library(psych)
library(tidyverse)
library(corrplot)

##Parameters
free_play_file <- "~/Desktop/BABIES/manber_sleep/data/pcirs_freeplay_manber.xlsx"
```

```{r}
free_play <-
  readxl::read_excel(free_play_file, sheet = "data")
```


# Calculate reliability at level of two-minute interval
```{r reliability_2min}
#sensitivity
sens <- 
  free_play %>%
  select(
    Sens_ER,
    Sens_LK
  ) %>% 
  na.omit()
ICC(sens)

#intrusiveness
intrus <- 
  free_play %>%
  select(
    Intrus_ER,
    Intrus_LK
  ) %>% 
  na.omit()
ICC(intrus)

#cognitive stimulation
stim <- 
  free_play %>%
  select(
    Stim_ER,
    Stim_LK
  ) %>% 
  na.omit()
ICC(stim)

#positive regard
posreg <- 
  free_play %>%
  select(
    PosReg_ER,
    PosReg_LK
  ) %>% 
  na.omit()
ICC(posreg)

#negative mood
negmood <- 
  free_play %>%
  select(
    NegMood_ER,
    NegMood_LK
  ) %>% 
  na.omit()
ICC(negmood)
```

# Calculate reliability at level of average across Free Play
```{r reliability_av}
#wrangle data 
free_play_means <- 
  free_play %>% 
  select(
    ID,
    Episode,
    Sens_ER:Atten_LK
  ) %>% 
  gather(key1, value, Sens_ER:Atten_LK) %>% 
  unite(key2, Episode, key1, sep = "_") %>% 
  spread(key2, value) %>% 
  group_by(ID) %>% 
  mutate(
    sens_M_ER = mean(
      c(
        `1_Sens_ER`, 
        `2_Sens_ER`, 
        `3_Sens_ER`, 
        `4_Sens_ER`, 
        `5_Sens_ER`
      ), 
      na.rm = TRUE
    ),
    sens_M_LK = mean(
      c(
        `1_Sens_LK`, 
        `2_Sens_LK`, 
        `3_Sens_LK`, 
        `4_Sens_LK`, 
        `5_Sens_LK`
      ), 
      na.rm = TRUE
    ),
    intrus_M_ER = mean(
      c(
        `1_Intrus_ER`, 
        `2_Intrus_ER`, 
        `3_Intrus_ER`, 
        `4_Intrus_ER`, 
        `5_Intrus_ER`
      ),
      na.rm = TRUE
    ),
    intrus_M_LK = mean(
      c(
        `1_Intrus_LK`, 
        `2_Intrus_LK`, 
        `3_Intrus_LK`, 
        `4_Intrus_LK`, 
        `5_Intrus_LK`
      ),
      na.rm = TRUE
    ),
    posreg_M_ER = mean(
      c(
        `1_PosReg_ER`, 
        `2_PosReg_ER`, 
        `3_PosReg_ER`, 
        `4_PosReg_ER`, 
        `5_PosReg_ER`
      ),
      na.rm = TRUE
    ),
    posreg_M_LK = mean(
      c(
        `1_PosReg_LK`, 
        `2_PosReg_LK`, 
        `3_PosReg_LK`, 
        `4_PosReg_LK`, 
        `5_PosReg_LK`
      ),
      na.rm = TRUE
    ),
    stim_M_ER = mean(
      c(
        `1_Stim_ER`, 
        `2_Stim_ER`, 
        `3_Stim_ER`, 
        `4_Stim_ER`, 
        `5_Stim_ER`
      ),
      na.rm = TRUE
    ),
    stim_M_LK = mean(
      c(
        `1_Stim_LK`, 
        `2_Stim_LK`, 
        `3_Stim_LK`, 
        `4_Stim_LK`, 
        `5_Stim_LK`
      ),
      na.rm = TRUE
    )
  ) %>% 
  ungroup()
```

``` {r}
#sensitivity
sensM <- 
  free_play_means %>%
  select(
    sens_M_ER,
    sens_M_LK
  ) %>% 
  na.omit(sensM)
ICC(sensM)

#instrusiveness
intrusM <- 
  free_play_means %>%
  select(
    intrus_M_ER,
    intrus_M_LK
  ) %>% 
  na.omit(intrusM)
ICC(intrusM)

#positive regard
posregM <- 
  free_play_means %>%
  select(
    posreg_M_ER,
    posreg_M_LK
  ) %>% 
  na.omit(posregM)
ICC(posregM)

#cognitive stimulation
stimM <- 
  free_play_means %>%
  select(
    stim_M_ER,
    stim_M_LK
  ) %>% 
  na.omit(stimM)
ICC(stimM)

```

# Determine final scores and reformat to wide-form
```{r final_ratings}
#Use LK's scores as primary. If LK didn't code, use ER's scores. If there are consensus scores, use consensus scores.
final_scores <- function(lk_score, er_score, con_score) {
  case_when(
    is.na(lk_score) ~ er_score,
    !is.na(con_score) ~ con_score,
    !is.na(er_score) & is.na(con_score) ~ lk_score,
    is.na(er_score) & is.na(con_score) ~ lk_score
  )
}
```

```{r}
free_play_lf <-
  free_play %>%
  mutate(
    sens_fin = final_scores(Sens_LK, Sens_ER, Sens_Con),
    intrus_fin = final_scores(Intrus_LK, Intrus_ER, Intrus_Con),
    posreg_fin = final_scores(PosReg_LK, PosReg_ER, PosReg_Con),
    stim_fin = final_scores(Stim_LK, Stim_ER, Stim_Con),
    detach_fin = final_scores(Detach_LK, Detach_ER, Detach_Con),
    negreg_fin = final_scores(NegReg_LK, NegReg_ER, NegReg_Con),
    posmood_fin = final_scores(PosMood_LK, PosMood_ER, PosMood_Con),
    negmood_fin = final_scores(NegMood_LK, NegMood_ER, NegMood_Con)
  ) %>% 
  select(
    ID,
    Episode,
    sens_fin:negmood_fin
  )
```

```{r}
free_play_wf <-
  free_play_lf %>% 
  gather(key1, value, sens_fin:negmood_fin) %>% 
  unite(key2, Episode, key1, sep = "_") %>% 
  spread(key2, value) %>% 
  group_by(ID) %>% 
  mutate(
    sens_M = mean(
      c(
        `1_sens_fin`, 
        `2_sens_fin`, 
        `3_sens_fin`, 
        `4_sens_fin`, 
        `5_sens_fin`
      ),
      na.rm = TRUE
    ),
    intrus_M = mean(
      c(
        `1_intrus_fin`, 
        `2_intrus_fin`, 
        `3_intrus_fin`, 
        `4_intrus_fin`, 
        `5_intrus_fin`
      ),
      na.rm = TRUE
    ),
    posreg_M = mean(
      c(
        `1_posreg_fin`, 
        `2_posreg_fin`, 
        `3_posreg_fin`, 
        `4_posreg_fin`, 
        `5_posreg_fin`
      ),
      na.rm = TRUE
    ),
    stim_M = mean(
      c(
        `1_stim_fin`, 
        `2_stim_fin`, 
        `3_stim_fin`, 
        `4_stim_fin`, 
        `5_stim_fin`),
      na.rm = TRUE
    ),
    detach_M = mean(
      c(
        `1_detach_fin`, 
        `2_detach_fin`, 
        `3_detach_fin`, 
        `4_detach_fin`, 
        `5_detach_fin`),
      na.rm = TRUE
    ),
    negreg_M = mean(
      c(
        `1_negreg_fin`, 
        `2_negreg_fin`, 
        `3_negreg_fin`, 
        `4_negreg_fin`, 
        `5_negreg_fin`
      ),
      na.rm = TRUE
    ),
    posmood_M = mean(
      c(
        `1_posmood_fin`, 
        `2_posmood_fin`, 
        `3_posmood_fin`, 
        `4_posmood_fin`, 
        `5_posmood_fin`),
      na.rm = TRUE
    ),
    negmood_M = mean(
      c(
        `1_negmood_fin`, 
        `2_negmood_fin`, 
        `3_negmood_fin`, 
        `4_negmood_fin`, 
        `5_negmood_fin`
      ),
      na.rm = TRUE
    )
  ) %>% 
  ungroup()
```

# Internal consistency across the five 2-minute intervals
```{r internal_consistency}
#sensitivity
sens_fin <- free_play_wf %>%
  select(
    `1_sens_fin`,
    `2_sens_fin`,
    `3_sens_fin`,
    `4_sens_fin`,
    `5_sens_fin`
  )
psych::alpha(sens_fin)

#instrusiveness
intrus_fin <- free_play_wf %>%
  select(
    `1_intrus_fin`,
    `2_intrus_fin`,
    `3_intrus_fin`,
    `4_intrus_fin`,
    `5_intrus_fin`
  )
psych::alpha(intrus_fin)

#positive regard
posreg_fin <- free_play_wf %>%
  select(
    `1_posreg_fin`,
    `2_posreg_fin`,
    `3_posreg_fin`,
    `4_posreg_fin`,
    `5_posreg_fin`
  )
psych::alpha(posreg_fin)

#cognitive stimulation
stim_fin <- free_play_wf %>%
  select(
    `1_stim_fin`,
    `2_stim_fin`,
    `3_stim_fin`,
    `4_stim_fin`,
    `5_stim_fin`
  )
psych::alpha(stim_fin)

detach_fin <- free_play_wf %>%
  select(
    `1_detach_fin`,
    `2_detach_fin`,
    `3_detach_fin`,
    `4_detach_fin`,
    `5_detach_fin`
  )
psych::alpha(detach_fin)
```


