---
title: "Wrangle the Actigraphy Data"
output: html_notebook
---

###Load data
```{r load data}
##Libraries
library(lubridate)
library(tidyverse)

##Parameters

#summary maternal actigraphy scores 
maternal_actigraphy_summary_file <- "~/Desktop/BABIES/manber_sleep/data/Actigraphy Export File_maternal_caregiving_02.21.18_SLEEPSUM.csv"

#daily maternal actigraphy scores

maternal_actigraphy_daily_file <- "~/Desktop/BABIES/manber_sleep/data/Actigraphy Export File_maternal_caregiving_02.21.18_SLEEPSUM.csv"

#load file with free play date
freeplay_date_file <- "~/Desktop/BABIES/manber_sleep/data/freeplay_date.csv"
```

###Wrangle summary scores
```{r summary}
maternal_actigraphy_summary <- read_csv(maternal_actigraphy_summary_file)

maternal_actigraphy_summary <-
  maternal_actigraphy_summary %>% 
  gather(key1, value, duration:avg_sleep_b) %>% 
  unite(key2, interval_number, key1, sep = "_") %>% 
  spread(key2, value) 
```

##Wrangle nightly scores
```{r nightly}
#reformat dates using lubridate
mact$start_date <- mdy(mact$start_date)
fp_date$fp_date <- mdy(fp_date$date_fp)
#merge with free play date file
mact <- merge(mact, fp_date, by ="ID", all = T)

#match free play date
mact$night_bf <- mact$fp_date - days(1) #date of night before is free play date - 1 day
mact$night_bf2 <- ifelse(mact$night_bf == mact$start_date, 1, 0)
mact$night_aft <- ifelse(mact$fp_date == mact$start_date, 1, 0) #night after is the same date as the free play

mact_bf <- subset(mact, night_bf2 == 1) #data from the night before the free play
mact_bf <- mact_bf %>%
  group_by(ID) %>%
  summarise(
    wake_time = sum(wake_time),
    sleep_time = sum(sleep_time)
  )
mact_bf <- rename(mact_bf, wake_timebf = wake_time)
mact_bf <- rename(mact_bf, sleep_timebf = sleep_time)

mact_aft <- subset(mact, night_aft == 1) #data from the night after the free play
mact_aft <- mact_aft %>%
  group_by(ID) %>%
  summarise(
    wake_time = sum(wake_time),
    sleep_time = sum(sleep_time)
  )

mact_aft <- rename(mact_aft, wake_timeaf = wake_time)
mact_aft <- rename(mact_aft, sleep_timeaf = sleep_time)

mact_fp <- merge(mact_bf, mact_aft, by = "ID", all = T)
mact_fp <- mact_fp %>%
  select(
    ID, 
    wake_timebf,
    sleep_timebf,
    wake_timeaf,
    sleep_timeaf
  )
```

###Distributions of summary scores
```{r summary_plot}
ggplot(mact_SUM, aes(x = n_nights)) + 
  geom_histogram(bins = 30, position = "dodge", fill= "gray", color = "black") +
  theme_bw() 

ggplot(mact_SUM, aes(x = av_waketime)) + 
  geom_histogram(bins = 30, position = "dodge", fill= "gray", color = "black") +
  theme_bw() 

#square root transformed
ggplot(mact_SUM, aes(x = sqrt(av_waketime))) + 
  geom_histogram(bins = 30, position = "dodge", fill= "gray", color = "black") +
  theme_bw() 

ggplot(mact_SUM, aes(x = av_sleeptime)) + 
  geom_histogram(bins = 30, position = "dodge", fill= "gray", color = "black") +
  theme_bw() 
```

###Distributions of daily scores
```{r daily_plot}
#night before free play
ggplot(mact_fp, aes(x = sleep_timebf)) + 
  geom_histogram(bins = 30, position = "dodge", fill= "gray", color = "black") +
  theme_bw() 

ggplot(mact_fp, aes(x = wake_timebf)) + 
  geom_histogram(bins = 30, position = "dodge", fill= "gray", color = "black") +
  theme_bw() 

#sqrt transformed
ggplot(mact_fp, aes(x = sqrt(wake_timebf))) + 
  geom_histogram(bins = 30, position = "dodge", fill= "gray", color = "black") +
  theme_bw() 

#night after free play
ggplot(mact_fp, aes(x = sleep_timeaf)) + 
  geom_histogram(bins = 30, position = "dodge", fill= "gray", color = "black") +
  theme_bw() 

ggplot(mact_fp, aes(x = wake_timeaf)) + 
  geom_histogram(bins = 30, position = "dodge", fill= "gray", color = "black") +
  theme_bw() 

#sqrt transformed
ggplot(mact_fp, aes(x = sqrt(wake_timeaf))) + 
  geom_histogram(bins = 30, position = "dodge", fill= "gray", color = "black") +
  theme_bw() 
```

##Correlations across measures
```{r}
mact_all <- merge(mact_SUM, mact_fp, by = "ID", all = T)
corr_mact <- cor(mact_all, use = "pairwise.complete.obs")
corrplot(corr_mact, order = "hclust", tl.col='black', tl.cex=.75)
```

