---
title: "Score Sleep Questionnaires"
author: "Lucy King"
date: "2/25/2018"
output: html_document
---

```{r}
#Libraries
library(tidyverse)

#Parameters
questionnaires_file <- "~/Desktop/BABIES/manber_sleep/data/T3 questionnaires.csv"
```


```{r}
questionnaires <-
  read_csv(questionnaires_file)
glimpse(questionnaires)
```

##Score questionnaires
```{r}
questionnaires <-
  questionnaires %>% 
  mutate(
    ISI_total = #insomnia severity index
      ISI_T3_1_ISI_T3_1a + 
      ISI_T3_1_ISI_T3_1b + 
      ISI_T3_1_ISI_T3_1c + 
      ISI_T3_2 + 
      ISI_T3_3 + 
      ISI_T3_4 + 
      ISI_T3_5,
    ISIP_total = #post-partum insomnia severity index
      ISIP_T3_1_ISIP_T3_1a +
      ISIP_T3_1_ISIP_T3_1b +
      ISIP_T3_1_ISIP_T3_1c +
      ISIP_T3_3 +
      ISIP_T3_4 +
      ISIP_T3_5,
    EPDS_total = 
      EPDS_T3_1 +
      EPDS_T3_2 +
      EPDS_T3_3 +
      EPDS_T3_4 +
      EPDS_T3_5 +
      EPDS_T3_6 +
      EPDS_T3_7 +
      EPDS_T3_8 +
      EPDS_T3_9 +
      EPDS_T3_10,
    B_sleepnight = (`BISQ_T3_7#time_PPD_4c_1` * 60) + `BISQ_T3_7#time_PPD_4c_2`,
    B_sleepday = (`BISQ_T3_8#time_PPD_4c_1` * 60) + `BISQ_T3_8#time_PPD_4c_2`,
    B_nightwakeful = (`BISQ_T3_10#time_PPD_4c_1` * 60) + `BISQ_T3_10#time_PPD_4c_2`,
    B_gotosleep = (`BISQ_T3_11#time_PPD_4c_1` * 60) + `BISQ_T3_11#time_PPD_4c_2`
  ) %>% 
  select(
    ID,
    ISI_total:B_gotosleep
  )

```

```{r}
ggplot(questionnaires, aes(x = ISI_total)) +
  geom_histogram(bins = 30, position = "dodge", fill = "gray", color = "black") +
  theme_bw()

ggplot(questionnaires, aes(x = ISIP_total)) +
  geom_histogram(bins = 30, position = "dodge", fill = "gray", color = "black") +
  theme_bw()

ggplot(questionnaires, aes(x = EPDS_total)) +
  geom_histogram(bins = 30, position = "dodge", fill = "gray", color = "black") +
  theme_bw()
```


